'use client';
import { useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowDownRight, ArrowUpRight, Bell, ChevronDown, CircleHelp, Clock3, Command, Compass, ExternalLink, Eye, Flame, LayoutDashboard, Menu, MoreHorizontal, Plus, Radio, Search, Settings2, ShieldCheck, Sparkles, Wallet, X } from 'lucide-react';

const chartData = [
 { day:'Sep 17', tvl:21.8, fees:17.2 }, { day:'Sep 18', tvl:22.5, fees:18.4 }, { day:'Sep 19', tvl:21.9, fees:16.7 }, { day:'Sep 20', tvl:24.4, fees:20.1 }, { day:'Sep 21', tvl:25.8, fees:22.3 }, { day:'Sep 22', tvl:24.9, fees:21.6 }, { day:'Sep 23', tvl:27.4, fees:23.8 }
];
const projects = [
 {name:'ARC',ticker:'ARC',type:'Launchpad',color:'#c2f970',mark:'A',tvl:'$8.42M',change:'+12.8%',fee:'$42.8K',users:'18.2K',status:'Live'},
 {name:'Neon Protocol',ticker:'NEON',type:'DeFi · DEX',color:'#a18aff',mark:'N',tvl:'$6.18M',change:'+8.4%',fee:'$28.6K',users:'12.4K',status:'Live'},
 {name:'Orbit Finance',ticker:'ORBT',type:'Lending',color:'#80cfff',mark:'O',tvl:'$4.72M',change:'+4.1%',fee:'$16.2K',users:'8.6K',status:'Live'},
 {name:'Mosaic',ticker:'MOS',type:'Liquid staking',color:'#ff9e79',mark:'M',tvl:'$3.91M',change:'−2.3%',fee:'$9.8K',users:'6.1K',status:'Live'},
 {name:'Arcade',ticker:'ARCD',type:'Gaming',color:'#fd77aa',mark:'✳',tvl:'$2.36M',change:'+18.6%',fee:'$7.4K',users:'4.8K',status:'New'},
];
const updates = [
 {icon:Sparkles,color:'#c2f970',title:'Arcade launches on ARC',text:'New gaming protocol joins the ecosystem',time:'2h ago',tag:'LAUNCH'},
 {icon:ArrowUpRight,color:'#80cfff',title:'Neon Protocol v2 is live',text:'Concentrated liquidity is now available',time:'5h ago',tag:'UPGRADE'},
 {icon:ShieldCheck,color:'#a18aff',title:'Orbit completes security audit',text:'Audit report published by Halborn',time:'1d ago',tag:'SECURITY'},
];
function MetricCard({label,value,change,positive,icon:Icon}:any){return <div className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={16}/></div><div className="metric-value">{value}</div><div className="metric-foot"><span className={positive?'positive':'negative'}>{positive?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {change}</span><span>vs last 7 days</span></div></div>}
export default function Home(){
 const [range,setRange]=useState('7D'); const [active,setActive]=useState('Overview'); const [search,setSearch]=useState(''); const [mobileOpen,setMobileOpen]=useState(false); const [watching,setWatching]=useState<string[]>(['ARC','NEON']);
 const filtered=projects.filter(p=>`${p.name} ${p.ticker} ${p.type}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="shell">
  <aside className={`sidebar ${mobileOpen?'mobile-open':''}`}>
   <div className="brand"><div className="brand-mark"><span/></div><span>arc<span className="brand-light">watch</span></span><button className="mobile-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>
   <div className="network"><span className="network-dot"/> ARC Network <ChevronDown size={14}/><span className="network-main">MAINNET</span></div>
   <div className="nav-label">WORKSPACE</div>
   <nav>{[['Overview',LayoutDashboard],['Ecosystem',Compass],['Launchpad',Sparkles],['Watchlist',Eye]].map(([label,Icon]:any)=><button key={label} className={`nav-item ${active===label?'selected':''}`} onClick={()=>{setActive(label);setMobileOpen(false)}}><Icon size={17}/><span>{label}</span>{label==='Ecosystem'&&<span className="nav-count">24</span>}</button>)}</nav>
   <div className="nav-label tools-label">TOOLS</div><nav><button className="nav-item" onClick={()=>setActive('Alerts')}><Bell size={17}/><span>Alerts</span><span className="alert-dot"/></button><button className="nav-item" onClick={()=>setActive('Analytics')}><Activity size={17}/><span>Analytics</span></button></nav>
   <div className="sidebar-bottom"><div className="upgrade-card"><div className="upgrade-icon"><Flame size={16}/></div><div><b>Build on ARC</b><span>Explore the ecosystem</span></div><ExternalLink size={14}/></div><button className="nav-item"><Settings2 size={17}/><span>Settings</span></button><div className="profile"><div className="avatar">JW</div><div className="profile-text"><b>Jasper Wong</b><span>Free plan</span></div><MoreHorizontal size={18}/></div></div>
  </aside>
  <section className="main-area"><header className="topbar"><button className="hamburger" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={19}/></button><div className="breadcrumbs"><span>Workspace</span><span className="slash">/</span><b>{active}</b></div><div className="top-actions"><div className="live-indicator"><span/> LIVE DATA</div><button className="icon-button"><CircleHelp size={17}/></button><button className="icon-button notification"><Bell size={17}/><i/></button><div className="top-avatar">JW</div></div></header>
  <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> ECOSYSTEM INTELLIGENCE <span className="eyebrow-line"/></div><h1>ARC <span>Ecosystem</span></h1><p className="subtitle">The pulse of everything building on ARC.</p></div><button className="watch-button" onClick={()=>setWatching(watching.includes('ARC')?watching.filter(x=>x!=='ARC'):[...watching,'ARC'])}><Plus size={16}/>{watching.includes('ARC')?'Watching ARC':'Add to watchlist'}</button></div>
  <div className="snapshot-strip"><div className="snapshot-live"><span className="pulse-dot"/> NETWORK STATUS</div><div className="snapshot-ok">All systems operational</div><span className="snapshot-divider"/><div className="snapshot-stat">Block height <b>18,492,071</b></div><span className="snapshot-divider"/><div className="snapshot-stat">Avg. block time <b>1.2s</b></div><span className="snapshot-divider"/><div className="snapshot-stat">Gas <b>0.003 ARC</b></div><div className="snapshot-updated"><Clock3 size={13}/> Updated 2 min ago</div></div>
  <div className="section-head"><div><div className="section-kicker">NETWORK OVERVIEW</div><h2>By the numbers</h2></div><button className="period-select">Last 7 days <ChevronDown size={14}/></button></div>
  <div className="metrics-grid"><MetricCard label="Total value locked" value="$27.4M" change="12.8%" positive icon={Wallet}/><MetricCard label="Fees generated" value="$184.6K" change="8.2%" positive icon={Activity}/><MetricCard label="Active projects" value="24" change="3 new" positive icon={Compass}/><MetricCard label="Unique users" value="52.8K" change="2.4%" positive icon={Eye}/></div>
  <div className="chart-card"><div className="chart-head"><div><div className="section-kicker">ECOSYSTEM GROWTH</div><h3>TVL &amp; protocol fees</h3></div><div className="chart-legend"><span><i className="legend-tvl"/> TVL</span><span><i className="legend-fees"/> Fees</span></div><div className="range-switch">{['24H','7D','30D','90D','ALL'].map(r=><button className={range===r?'on':''} onClick={()=>setRange(r)} key={r}>{r}</button>)}</div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:12,right:4,left:-24,bottom:0}}><defs><linearGradient id="tvlFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c2f970" stopOpacity={0.20}/><stop offset="100%" stopColor="#c2f970" stopOpacity={0}/></linearGradient><linearGradient id="feesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#92a5ff" stopOpacity={0.12}/><stop offset="100%" stopColor="#92a5ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#20252d" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:'#6f7783',fontSize:11}} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#6f7783',fontSize:11}} tickFormatter={v=>`$${v}M`}/><Tooltip contentStyle={{background:'#151920',border:'1px solid #303640',borderRadius:8,color:'#eef0eb',fontSize:12}}/><Area type="monotone" dataKey="tvl" name="TVL" stroke="#c2f970" strokeWidth={2} fill="url(#tvlFill)"/><Area type="monotone" dataKey="fees" name="Fees" stroke="#92a5ff" strokeWidth={1.5} fill="url(#feesFill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span>TVL <b>$27.4M</b> <em>↑ 12.8%</em></span><span>7D fees <b>$184.6K</b> <em>↑ 8.2%</em></span><span className="source-note">Source: ARC on-chain indexer</span></div></div>
  <div className="lower-grid"><section className="projects-card"><div className="panel-head"><div><div className="section-kicker">ON-CHAIN PERFORMANCE</div><h3>Top projects</h3></div><button className="view-all" onClick={()=>setActive('Ecosystem')}>View ecosystem <ArrowUpRight size={14}/></button></div><div className="table-tools"><div className="search-box"><Search size={15}/><input placeholder="Search projects..." value={search} onChange={e=>setSearch(e.target.value)}/><kbd><Command size={10}/> K</kbd></div><button className="filter-button"><Settings2 size={14}/> Filters</button></div><div className="table-scroll"><table><thead><tr><th>PROJECT</th><th>TVL</th><th>7D CHANGE</th><th>FEES (7D)</th><th>USERS</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.ticker}><td><div className="project-cell"><div className="project-mark" style={{'--project-color':p.color} as React.CSSProperties}>{p.mark}</div><div><b>{p.name}</b><span>{p.ticker} <i>·</i> {p.type}</span></div></div></td><td className="mono">{p.tvl}</td><td><span className={p.change.includes('−')?'negative':'positive'}>{!p.change.includes('−')&&<ArrowUpRight size={12}/>} {p.change}</span></td><td className="mono">{p.fee}</td><td className="mono muted-cell">{p.users}</td><td><button aria-label={`Watch ${p.name}`} className={`star-button ${watching.includes(p.ticker)?'starred':''}`} onClick={()=>setWatching(watching.includes(p.ticker)?watching.filter(x=>x!==p.ticker):[...watching,p.ticker])}>✳</button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty-state">No projects match “{search}”</div>}</div><div className="table-bottom"><span>Showing <b>{filtered.length}</b> of 24 projects</span><button onClick={()=>setActive('Ecosystem')}>Explore all projects <ArrowUpRight size={13}/></button></div></section>
  <section className="updates-card"><div className="panel-head"><div><div className="section-kicker">WHAT'S HAPPENING</div><h3>Latest updates</h3></div><button className="dots-button"><MoreHorizontal size={18}/></button></div><div className="update-list">{updates.map((u,i)=><article className="update" key={u.title}><div className="update-icon" style={{'--update-color':u.color} as React.CSSProperties}><u.icon size={16}/></div><div className="update-content"><div className="update-title-line"><b>{u.title}</b><span className="update-tag">{u.tag}</span></div><p>{u.text}</p><span className="update-time">{u.time}</span></div></article>)}</div><button className="all-updates" onClick={()=>setActive('Updates')}>View all updates <ArrowUpRight size={14}/></button><div className="signal-card"><div className="signal-top"><span><Radio size={14}/> SIGNAL CHECK</span><span className="signal-live">● LIVE</span></div><div className="signal-message">The ecosystem is <b>picking up momentum.</b></div><div className="signal-foot"><span>TVL is up 12.8% this week</span><span>↗</span></div></div></section></div>
  <footer><span>© 2026 ARC WATCH <i>·</i> COMMUNITY BUILT</span><span>DATA IS FOR INFORMATIONAL PURPOSES <i>·</i> <a href="#">Documentation</a> <a href="#">Feedback</a></span></footer></div></section>
  {mobileOpen&&<button className="mobile-scrim" onClick={()=>setMobileOpen(false)} aria-label="Close menu"/>}</main>
}
