'use client';
import { useEffect, useState } from 'react';
import LaunchpadPage from './launchpad-page';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowDownRight, ArrowUpRight, Bell, ChevronDown, CircleHelp, Clock3, Command, Compass, ExternalLink, Eye, Flame, LayoutDashboard, Menu, Moon, MoreHorizontal, Plus, Radio, Search, Settings2, ShieldCheck, Sparkles, Sun, Wallet, X } from 'lucide-react';

const chartData = [
 { day:'Sep 17', tvl:21.8, fees:17.2 }, { day:'Sep 18', tvl:22.5, fees:18.4 }, { day:'Sep 19', tvl:21.9, fees:16.7 }, { day:'Sep 20', tvl:24.4, fees:20.1 }, { day:'Sep 21', tvl:25.8, fees:22.3 }, { day:'Sep 22', tvl:24.9, fees:21.6 }, { day:'Sep 23', tvl:27.4, fees:23.8 }
];
const projects = [
 {name:'ARC',ticker:'ARC',type:'Launchpad',color:'#c2f970',mark:'A',tvl:'$8.42M',change:'+12.8%',fee:'$42.8K',users:'18.2K',status:'Live'},
 {name:'Neon Protocol',ticker:'NEON',type:'DeFi · DEX',color:'#a18aff',mark:'N',tvl:'$6.18M',change:'+8.4%',fee:'$28.6K',users:'12.4K',status:'Live'},
 {name:'Orbit Finance',ticker:'ORBT',type:'Lending',color:'#80cfff',mark:'O',tvl:'$4.72M',change:'+4.1%',fee:'$16.2K',users:'8.6K',status:'Live'},
 {name:'Mosaic',ticker:'MOS',type:'Liquid staking',color:'#ff9e79',mark:'M',tvl:'$3.91M',change:'−2.3%',fee:'$9.8K',users:'6.1K',status:'Live'},
 {name:'Arcade',ticker:'ARCD',type:'Gaming',color:'#fd77aa',mark:'✳',tvl:'$2.36M',change:'+18.6%',fee:'$7.4K',users:'4.8K',status:'New'},
];
const updates = [
 {icon:Sparkles,color:'#c2f970',title:'Arcade launches on ARC',text:'New gaming protocol joins the ecosystem',time:'2h ago',tag:'LAUNCH'},
 {icon:ArrowUpRight,color:'#80cfff',title:'Neon Protocol v2 is live',text:'Concentrated liquidity is now available',time:'5h ago',tag:'UPGRADE'},
 {icon:ShieldCheck,color:'#a18aff',title:'Orbit completes security audit',text:'Audit report published by Halborn',time:'1d ago',tag:'SECURITY'},
];
function MetricCard({label,value,change,positive,icon:Icon,language='en'}:any){return <div className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={16}/></div><div className="metric-value">{value}</div><div className="metric-foot"><span className={positive?'positive':'negative'}>{positive?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {change}</span><span>{language==='zh'?'较过去 7 天':'vs last 7 days'}</span></div></div>}
export default function Home(){
 const [range,setRange]=useState('7D'); const [active,setActive]=useState('Overview'); const [search,setSearch]=useState(''); const [mobileOpen,setMobileOpen]=useState(false); const [watching,setWatching]=useState<string[]>(['ARC','NEON']);
 const [isDark,setIsDark]=useState(true); const [language,setLanguage]=useState<'en'|'zh'>('en'); const tr=(en:string,zh:string)=>language==='zh'?zh:en;
 useEffect(()=>{const saved=localStorage.getItem('arcwatch-theme');if(saved==='light')setIsDark(false);const savedLanguage=localStorage.getItem('arcwatch-language');if(savedLanguage==='zh')setLanguage('zh')},[]);
 useEffect(()=>{document.documentElement.dataset.theme=isDark?'dark':'light';localStorage.setItem('arcwatch-theme',isDark?'dark':'light')},[isDark]); useEffect(()=>{document.documentElement.lang=language==='zh'?'zh-CN':'en';localStorage.setItem('arcwatch-language',language)},[language]);
 const filtered=projects.filter(p=>`${p.name} ${p.ticker} ${p.type} ${language==='zh'?({Launchpad:'发射台','DeFi · DEX':'去中心化交易所',Lending:'借贷','Liquid staking':'流动性质押',Gaming:'游戏'} as Record<string,string>)[p.type]||'': ''}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="shell">
  <aside className={`sidebar ${mobileOpen?'mobile-open':''}`}>
   <div className="brand"><div className="brand-mark"><span/></div><span>arc<span className="brand-light">watch</span></span><button className="mobile-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>
   <div className="network"><span className="network-dot"/> {tr('ARC Network','ARC 网络')} <ChevronDown size={14}/><span className="network-main">MAINNET</span></div>
   <div className="nav-label">{tr('WORKSPACE','工作区')}</div>
   <nav>{[['Overview',LayoutDashboard],['Ecosystem',Compass],['Launchpad',Sparkles],['Watchlist',Eye]].map(([label,Icon]:any)=><button key={label} className={`nav-item ${active===label?'selected':''}`} onClick={()=>{setActive(label);setMobileOpen(false)}}><Icon size={17}/><span>{tr(label,({Overview:'概览',Ecosystem:'生态',Launchpad:'发射台',Watchlist:'关注列表'} as Record<string,string>)[label]||label)}</span>{label==='Ecosystem'&&<span className="nav-count">24</span>}</button>)}</nav>
   <div className="nav-label tools-label">{tr('TOOLS','工具')}</div><nav><button className="nav-item" onClick={()=>setActive('Alerts')}><Bell size={17}/><span>{tr('Alerts','提醒')}</span><span className="alert-dot"/></button><button className="nav-item" onClick={()=>setActive('Analytics')}><Activity size={17}/><span>{tr('Analytics','分析')}</span></button></nav>
   <div className="sidebar-bottom"><div className="upgrade-card"><div className="upgrade-icon"><Flame size={16}/></div><div><b>{tr('Build on ARC','在 ARC 上构建')}</b><span>{tr('Explore the ecosystem','探索生态')}</span></div><ExternalLink size={14}/></div><button className="nav-item"><Settings2 size={17}/><span>{tr('Settings','设置')}</span></button><div className="profile"><div className="avatar">JW</div><div className="profile-text"><b>Jasper Wong</b><span>{tr('Free plan','免费计划')}</span></div><MoreHorizontal size={18}/></div></div>
  </aside>
  <section className="main-area"><header className="topbar"><button className="hamburger" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={19}/></button><div className="breadcrumbs"><span>{tr('Workspace','工作区')}</span><span className="slash">/</span><b>{tr(active,({Overview:'概览',Ecosystem:'生态',Launchpad:'发射台',Watchlist:'关注列表',Alerts:'提醒',Analytics:'分析',Updates:'动态'} as Record<string,string>)[active]||active)}</b></div><div className="top-actions"><div className="live-indicator"><span/> {tr('LIVE DATA','实时数据')}</div><button className="language-button" onClick={()=>setLanguage(language==='en'?'zh':'en')} aria-label={language==='en'?'Switch to Chinese':'切换为英文'} title={language==='en'?'Switch to Chinese':'切换为英文'}>{language==='en'?'EN':'CN'}</button><button className="icon-button" aria-label={isDark?'切换到白天模式':'切换到夜间模式'} title={isDark?'白天模式':'夜间模式'} onClick={()=>setIsDark(!isDark)}>{isDark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="icon-button help-button"><CircleHelp size={17}/></button><button className="icon-button notification"><Bell size={17}/><i/></button><div className="top-avatar">JW</div></div></header>
  {active==='Launchpad'?<LaunchpadPage language={language} isDark={isDark}/>:<div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> {tr('ECOSYSTEM INTELLIGENCE','生态情报')} <span className="eyebrow-line"/></div><h1>ARC <span>{tr('Ecosystem','生态总览')}</span></h1><p className="subtitle">{tr('The pulse of everything building on ARC.','洞察所有正在 ARC 上构建的项目。')}</p></div><button className="watch-button" onClick={()=>setWatching(watching.includes('ARC')?watching.filter(x=>x!=='ARC'):[...watching,'ARC'])}><Plus size={16}/>{watching.includes('ARC')?tr('Watching ARC','已关注 ARC'):tr('Add to watchlist','加入关注')}</button></div>
  <div className="snapshot-strip"><div className="snapshot-live"><span className="pulse-dot"/>{tr('NETWORK STATUS','网络状态')}</div><div className="snapshot-ok">{tr('All systems operational','所有系统运行正常')}</div><span className="snapshot-divider"/><div className="snapshot-stat">{tr('Block height','区块高度')} <b>18,492,071</b></div><span className="snapshot-divider"/><div className="snapshot-stat">{tr('Avg. block time','平均出块时间')} <b>1.2s</b></div><span className="snapshot-divider"/><div className="snapshot-stat">{tr('Gas','Gas 费用')} <b>0.003 ARC</b></div><div className="snapshot-updated"><Clock3 size={13}/> {tr('Updated 2 min ago','2 分钟前更新')}</div></div>
  <div className="section-head"><div><div className="section-kicker">{tr('NETWORK OVERVIEW','网络概览')}</div><h2>{tr('By the numbers','关键指标')}</h2></div><button className="period-select">{tr('Last 7 days','最近 7 天')} <ChevronDown size={14}/></button></div>
  <div className="metrics-grid"><MetricCard label={tr('Total value locked','总锁仓价值')} value="$27.4M" change="12.8%" positive icon={Wallet} language={language}/><MetricCard label={tr('Fees generated','费用收入')} value="$184.6K" change="8.2%" positive icon={Activity} language={language}/><MetricCard label={tr('Active projects','活跃项目')} value="24" change={tr('3 new','新增 3 个')} positive icon={Compass} language={language}/><MetricCard label={tr('Unique users','独立用户')} value="52.8K" change="2.4%" positive icon={Eye} language={language}/></div>
  <div className="chart-card"><div className="chart-head"><div><div className="section-kicker">{tr('ECOSYSTEM GROWTH','生态增长')}</div><h3>{tr('TVL & protocol fees','TVL 与协议费用')}</h3></div><div className="chart-legend"><span><i className="legend-tvl"/> TVL</span><span><i className="legend-fees"/> {tr('Fees','费用')}</span></div><div className="range-switch">{['24H','7D','30D','90D','ALL'].map(r=><button className={range===r?'on':''} onClick={()=>setRange(r)} key={r}>{r}</button>)}</div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:12,right:4,left:-24,bottom:0}}><defs><linearGradient id="tvlFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c2f970" stopOpacity={0.20}/><stop offset="100%" stopColor="#c2f970" stopOpacity={0}/></linearGradient><linearGradient id="feesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#92a5ff" stopOpacity={0.12}/><stop offset="100%" stopColor="#92a5ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke={isDark?'#20252d':'#e6e9e2'} vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:isDark?'#6f7783':'#798179',fontSize:11}} tickFormatter={(v:string)=>language==='zh'?`9月${v.match(/\d+/)?.[0]}日`:v} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{fill:isDark?'#6f7783':'#798179',fontSize:11}} tickFormatter={v=>`$${v}M`}/><Tooltip contentStyle={{background:isDark?'#151920':'#ffffff',border:`1px solid ${isDark?'#303640':'#dfe3da'}`,borderRadius:8,color:isDark?'#eef0eb':'#20251e',fontSize:12}}/><Area type="monotone" dataKey="tvl" name="TVL" stroke="#729c36" strokeWidth={2} fill="url(#tvlFill)"/><Area type="monotone" dataKey="fees" name={tr('Fees','费用')} stroke="#7588df" strokeWidth={1.5} fill="url(#feesFill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span>TVL <b>$27.4M</b> <em>↑ 12.8%</em></span><span>{tr('7D fees','7 日费用')} <b>$184.6K</b> <em>↑ 8.2%</em></span><span className="source-note">{tr('Source: ARC on-chain indexer','数据来源：ARC 链上索引器')}</span></div></div>
  <div className="lower-grid"><section className="projects-card"><div className="panel-head"><div><div className="section-kicker">{tr('ON-CHAIN PERFORMANCE','链上表现')}</div><h3>{tr('Top projects','热门项目')}</h3></div><button className="view-all" onClick={()=>setActive('Ecosystem')}>{tr('View ecosystem','查看生态')} <ArrowUpRight size={14}/></button></div><div className="table-tools"><div className="search-box"><Search size={15}/><input placeholder={tr('Search projects...','搜索项目…')} value={search} onChange={e=>setSearch(e.target.value)}/><kbd><Command size={10}/> K</kbd></div><button className="filter-button"><Settings2 size={14}/>{tr('Filters','筛选')}</button></div><div className="table-scroll"><table><thead><tr><th>{tr('PROJECT','项目')}</th><th>TVL</th><th>{tr('7D CHANGE','7日变化')}</th><th>{tr('FEES (7D)','费用（7日）')}</th><th>{tr('USERS','用户')}</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.ticker}><td><div className="project-cell"><div className="project-mark" style={{'--project-color':p.color} as React.CSSProperties}>{p.mark}</div><div><b>{p.name}</b><span>{p.ticker} <i>·</i> {language==='zh'?({Launchpad:'发射台','DeFi · DEX':'DeFi · 去中心化交易所',Lending:'借贷','Liquid staking':'流动性质押',Gaming:'游戏'} as Record<string,string>)[p.type]||p.type:p.type}</span></div></div></td><td className="mono">{p.tvl}</td><td><span className={p.change.includes('−')?'negative':'positive'}>{!p.change.includes('−')&&<ArrowUpRight size={12}/>} {p.change}</span></td><td className="mono">{p.fee}</td><td className="mono muted-cell">{p.users}</td><td><button aria-label={tr(`Watch ${p.name}`,`关注${p.name}`)} className={`star-button ${watching.includes(p.ticker)?'starred':''}`} onClick={()=>setWatching(watching.includes(p.ticker)?watching.filter(x=>x!==p.ticker):[...watching,p.ticker])}>✳</button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty-state">{tr(`No projects match “${search}”`,`没有匹配“${search}”的项目`)}</div>}</div><div className="table-bottom"><span>{tr('Showing','显示')} <b>{filtered.length}</b> {tr('of 24 projects','个项目，共 24 个')}</span><button onClick={()=>setActive('Ecosystem')}>{tr('Explore all projects','浏览全部项目')} <ArrowUpRight size={13}/></button></div></section>
  <section className="updates-card"><div className="panel-head"><div><div className="section-kicker">{tr("WHAT'S HAPPENING",'生态动态')}</div><h3>{tr('Latest updates','最新动态')}</h3></div><button className="dots-button"><MoreHorizontal size={18}/></button></div><div className="update-list">{updates.map((u,i)=><article className="update" key={u.title}><div className="update-icon" style={{'--update-color':u.color} as React.CSSProperties}><u.icon size={16}/></div><div className="update-content"><div className="update-title-line"><b>{language==='zh'?(['Arcade 登陆 ARC','Neon Protocol v2 正式上线','Orbit 完成安全审计'][i]):u.title}</b><span className="update-tag">{language==='zh'?(['上线','升级','安全'][i]):u.tag}</span></div><p>{language==='zh'?(['全新游戏协议加入 ARC 生态','集中流动性功能现已开放','Halborn 已发布安全审计报告'][i]):u.text}</p><span className="update-time">{language==='zh'?(['2 小时前','5 小时前','1 天前'][i]):u.time}</span></div></article>)}</div><button className="all-updates" onClick={()=>setActive('Updates')}>{tr('View all updates','查看全部动态')} <ArrowUpRight size={14}/></button><div className="signal-card"><div className="signal-top"><span><Radio size={14}/> {tr('SIGNAL CHECK','生态信号')}</span><span className="signal-live">● {tr('LIVE','实时')}</span></div><div className="signal-message">{tr('The ecosystem is ' ,'生态正在')}<b>{tr('picking up momentum.','加速增长。')}</b></div><div className="signal-foot"><span>{tr('TVL is up 12.8% this week','本周 TVL 上涨 12.8%')}</span><span>↗</span></div></div></section></div>
  <footer><span>© 2026 ARC WATCH <i>·</i> {tr('COMMUNITY BUILT','社区共建')}</span><span>{tr('DATA IS FOR INFORMATIONAL PURPOSES','数据仅供参考')} <i>·</i> <a href="#">{tr('Documentation','文档')}</a> <a href="#">{tr('Feedback','反馈')}</a></span></footer></div>} </section>
  {mobileOpen&&<button className="mobile-scrim" onClick={()=>setMobileOpen(false)} aria-label={tr('Close menu','关闭菜单')}/>}</main>
}
